sudo: required
dist: trusty
git:
  depth: 1
language: node_js
node_js:
- '6'
- '7'
- stable
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
matrix:
  fast_finish: true
install:
- npm install
before_script:
- export DBUS_SESSION_BUS_ADDRESS=/dev/null
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run test:ci
- echo $TRAVIS_BRANCH
- if [ $TRAVIS_BRANCH = 'develop' ]; then npm run build:ci https://s3-us-west-1.amazonaws.com/recipe-stage-client.blendtec.com/registration/
  --base-href /pages/product-registration-stage/; fi
- if [ $TRAVIS_BRANCH = 'master' ]; then npm run build:ci https://s3-us-west-1.amazonaws.com/recipe-client.blendtec.com/registration/
  --base-href /pages/product-registration/; fi
after_success:
- "./node_modules/.bin/codecov"
notifications:
  slack: blendtec:a5Z5i4z3iuWbHHDdlMRSMkiB
env:
  global:
deploy:
- provider: s3
  region: us-west-1
  access_key_id: AKIAJLMSNKBUNB4P3L4Q
  secret_access_key:
    secure: MO2vCEsQJX6PcELsP2zJ4RGlW3E80lIF7XVQg8yHF2gMt0T8R8ew4Uq2weCVB6iamsh4doNTRuSFZksMsUJ4+V50inMxW/NnYj/6mNf18VtynlntXwMKrH2zbORwv7ZTm+lXj6OCmXCjh3ic0YISFcXjAC4jwE1Ag2cm+XzQRXxYnHcmceu7WV/bgnnw/FogsWa2bNdwLVehYyEsxKveOaVel19bNuFAlA68vacAqp1RJV4vv1elg+nbFMP8bw8ngSo6SYHETMXIy7VXcpAt6ynRA7kiZqqTahAMn9tov3Z5ZY0ecm0OGSoDaX2B+Kh1ArIeWMI0UGh/jEKHP3WWNKEkbmFGprXg3wH3DERF0EIna+t0vWzEpEEtKvqvm/ntW4Dh7HqdIcPybylNq9WtWonIiMIfhu7EqmlzK9uPB8c/FxRJVg08j45v0c+e2IJog9+DBSKA7zh0DLHrfR5wcWzvaJW5rJha5l7O4CntXUOxipJodztw+0bbmi7jmXOVPAUsipVFaomMiXn0HroAOS+WFkxsuaDcJ5y2gAVDa5BfTY66ZuL7SwitCUzU6xuHpBZSBX/Hjx3q8W0Abh/Sd6r/yybWKCPstwiDXrtwvMK2xanZKTuxTaHaqUFVFo49CuTO4Ym004cLzxVG25mSKqh4voZnfWS7OENRW+pnp0w=
  bucket: recipe-client.blendtec.com
  local-dir: dist
  upload-dir: registration
  skip_cleanup: true
  acl: public_read
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: "./.travis/deploy.sh https://s3-us-west-1.amazonaws.com/recipe-client.blendtec.com/warranties"
  on:
    branch: master
- provider: s3
  region: us-west-1
  access_key_id: AKIAJLMSNKBUNB4P3L4Q
  secret_access_key:
    secure: MO2vCEsQJX6PcELsP2zJ4RGlW3E80lIF7XVQg8yHF2gMt0T8R8ew4Uq2weCVB6iamsh4doNTRuSFZksMsUJ4+V50inMxW/NnYj/6mNf18VtynlntXwMKrH2zbORwv7ZTm+lXj6OCmXCjh3ic0YISFcXjAC4jwE1Ag2cm+XzQRXxYnHcmceu7WV/bgnnw/FogsWa2bNdwLVehYyEsxKveOaVel19bNuFAlA68vacAqp1RJV4vv1elg+nbFMP8bw8ngSo6SYHETMXIy7VXcpAt6ynRA7kiZqqTahAMn9tov3Z5ZY0ecm0OGSoDaX2B+Kh1ArIeWMI0UGh/jEKHP3WWNKEkbmFGprXg3wH3DERF0EIna+t0vWzEpEEtKvqvm/ntW4Dh7HqdIcPybylNq9WtWonIiMIfhu7EqmlzK9uPB8c/FxRJVg08j45v0c+e2IJog9+DBSKA7zh0DLHrfR5wcWzvaJW5rJha5l7O4CntXUOxipJodztw+0bbmi7jmXOVPAUsipVFaomMiXn0HroAOS+WFkxsuaDcJ5y2gAVDa5BfTY66ZuL7SwitCUzU6xuHpBZSBX/Hjx3q8W0Abh/Sd6r/yybWKCPstwiDXrtwvMK2xanZKTuxTaHaqUFVFo49CuTO4Ym004cLzxVG25mSKqh4voZnfWS7OENRW+pnp0w=
  bucket: recipe-stage-client.blendtec.com
  local-dir: dist
  upload-dir: registration
  skip_cleanup: true
  acl: public_read
  on:
    branch: develop
- provider: script
  skip_cleanup: true
  script: "./.travis/deploy_stage.sh https://s3-us-west-1.amazonaws.com/recipe-stage-client.blendtec.com/warranties"
  on:
    branch: develop
